### ISSUE TITLE
Notify listeners when error sounds play in android

### ISSUE THREAD

**Issue by iampopal** [csdcorp/speech_to_text#73] opened 2020-04-21 09:03 UTC
After i listen and not say anything. 
Android play an error sound (dodot). 
I need an event to know when that sound happens to show user that text can't recognize.

You can change final result to true and notify Lister. 

I need a state to show user that the app is recognizing ur voice when internet is low.

**Comment by sowens-csd** [comment] 2020-04-21 11:02
You should get both an onError and onStatus callback when that happens. Both are set on the `Initialize` method.

**Comment by iampopal** [comment] 2020-04-21 11:11
Both of them not get notified
Please test it in the latest version of ur library

You can reproduce it by 
Start Listening 
And not say anything while having slow or no internet
Then stop listening

**Comment by sowens-csd** [comment] 2020-04-22 14:36
Thanks, I have another outstanding issue with the behaviour in no connection situations. I'll try that.

**Comment by sowens-csd** [comment] 2020-04-26 19:28
I haven't been able to reproduce this yet. I just tried with no Internet and it seems fine in the example app.  Each time I click the Start button I receive three notifications, the first is to the status listener with the value 'listening', then an error status of 'error_server' with permanent set to true, then a status listening with the value 'notListening'. Can you try this in the example app and let me know what your results are? 

I changed a couple of methods in the example app so I could see the notification sequence in the log. Here's the changed versions:

```
void errorListener(SpeechRecognitionError error) {
    print("Received error status: $error");
    setState(() {
      lastError = "${error.errorMsg} - ${error.permanent}";
    });
  }

  void statusListener(String status) {
    print("Received listener status: $status");
    setState(() {
      lastStatus = "$status";
    });
  }
```

The output I see when running this in Android Studio is:
```
I/flutter: Received listener status: listening
I/flutter: Received error status: SpeechRecognitionError msg: error_server, permanent: true
I/flutter: Received listener status: notListening
```

Perhaps the problem is when there is low rather than no Internet? In my test I simulated by turning off the wifi, maybe I need a wifi connection without Internet to see the result? If you're seeing different results can you let me know how you're testing?

**Comment by sowens-csd** [comment] 2020-05-19 12:35
Going to close this issue as I can't reproduce in my testing and don't have enough information to troubleshoot further.

**Closed by sowens-csd** 2020-05-19 12:35 UTC
Labels: Could not reproduce, waiting for response
