### ISSUE TITLE
if we not speak anything on iOS it won't letting know the user

### ISSUE THREAD

**Issue by alavalmahesh** [csdcorp/speech_to_text#182] opened 2021-03-09 12:46 UTC
if we not speak anything on iOS it won't letting know the user

**Comment by sowens-csd** [comment] 2021-03-09 14:11
I'm sorry, I don't understand the question. Could you give me more details of what you are expecting to see?

**Comment by alavalmahesh** [comment] 2021-03-09 15:15
Once I start session, if i am not speak anything for few minutes, its still continuing the session, its won't get stopping.

**Comment by sowens-csd** [comment] 2021-03-09 15:42
Yes, that's right iOS does not automatically stop the speech session. There's a property on the `listen` method `pauseFor` that automatically stops the speech session after the `Duration` you provide.

**Comment by alavalmahesh** [comment] 2021-03-11 06:59
pauseFor - not stopping the session

**Comment by sowens-csd** [comment] 2021-03-12 12:01
I just tested it in the example app and it seems to be working fine. Can you describe what problem you're seeing? Here's the modified version of the `listen` call I used in the example:

```dart
   speech.listen(
        onResult: resultListener,
        listenFor: Duration(seconds: 30),
        pauseFor: Duration(seconds: 2),
        partialResults: true,
        localeId: _currentLocaleId,
        onSoundLevelChange: soundLevelListener,
        cancelOnError: true,
        listenMode: ListenMode.confirmation);
```

**Comment by sowens-csd** [comment] 2021-03-16 13:17
Since it's working in the example app and issue #177 seems to be a duplicate of this and that is reported as working I'm going to close this. If you have more information or a new problem please let me know.

**Closed by sowens-csd** 2021-03-16 13:17 UTC
Labels: iOS, waiting for response
