### ISSUE TITLE
Speech to text plugin not detecting any words if you set locals other than default - Flutter 3.0

### ISSUE THREAD

**Issue by chorauoc** [csdcorp/speech_to_text#331] opened 2022-07-30 12:49 UTC
Hi,

Please note that plugin listen function not calling if we set locals while initialising the plugin , I have checked with Arabic, Hindi etc. and when i set this plugin not giving any outputs. This plugin was worked before and after updating to Flutter 3.0 this error occurred, Can you check this issue

Thanks

**Comment by sowens-csd** [comment] 2022-07-30 14:39
Thanks for reporting. Just to be sure I understand are you saying that if you use the `localeId` parameter on the `listen` method then you don't get any results? And you believe this is only occurring on Flutter 3.0 and later? 

What device / OS are you testing with? Have you verified that the problem is the same with the sample app?

**Comment by sowens-csd** [comment] 2022-07-30 14:55
I just tried the example app built with Flutter 3.0.4 running on an iPad with iOS 15.5 and it worked fine for both English and French. Can you provide any more details and let me know if you've tested the example app? 

Perhaps I'm misunderstanding the issue. You say '...if we set locals while initializing...' I interpreted that to mean the localeId but that's not set while initializing so perhaps I misunderstood.

**Comment by chorauoc** [comment] 2022-07-30 19:07
I was changing the locals using the language setting of the app of mine from English to Arabic etc, and I was testing this with Android mobile which Flutter 3.0, yes this was working fine till the Flutter update, however now in Android plugin is not giving me any outputs, So can you tell me what is the issue in Android.

Also I want to know, if I change any locals then that local need to present in the device lanes section or not ?

**Comment by sowens-csd** [comment] 2022-08-03 14:17
Yes, as far as I know the language you use has to be installed on the device. The list of locales that the plugin returns should all be supported. 

Have you tested this with the example app and are you getting the same behaviour? 

What version of Android are you testing against?

**Comment by sowens-csd** [comment] 2022-08-03 15:40
So the `locales` property on Android is returning the full list of languages supported by the speech recognizer. Other things I've read have suggested that a language has to be installed on the device to work for speech recognition. Can you try installing one of the languages you want to test with on the device and see if that changes the behaviour? I'll have to check again but my memory is that the way the `locales` list currently works is the closest I could get to the list of available languages. I don't think I was able to find an Android API that lists the installed languages.

**Comment by sowens-csd** [comment] 2022-08-08 15:30
Unfortunately I don't know of an error return that identifies this problem.

**Comment by sowens-csd** [comment] 2022-08-14 15:23
I'm going to close this issue because I think the original problem is resolved. Let me know if you have more questions.

**Closed by sowens-csd** 2022-08-14 15:23 UTC
Labels: waiting for response
