### ISSUE TITLE
[IOS] - Speech level

### ISSUE THREAD

**Issue by noraibrahimi** [csdcorp/speech_to_text#57] opened 2020-03-31 11:23 UTC
On IOS, speech level doesn't change, it always returns 0. This is not happening on Android.

**Comment by sowens-csd** [comment] 2020-03-31 11:52
Do you mean `lastSoundLevel`? If so then yes, that's as expected. I haven't implemented the sound level functionality on iOS yet. I have another issue open for that so if that's what you're looking for I'll close this one.

**Comment by noraibrahimi** [comment] 2020-03-31 11:56
Yes, lastSoundLevel. I didn't find anything regarding this issue therefore I opened a new one. 
Of course you can close it if it's a duplicate.

**Comment by sowens-csd** [comment] 2020-03-31 12:14
duplicate of #12

**Closed by sowens-csd** 2020-03-31 12:14 UTC
Labels: duplicate, waiting for response
