### ISSUE TITLE
Error in SpeechToText().initialize() in Flutter Web running in Safari browser 

### ISSUE THREAD

**Issue by LeoBali** [csdcorp/speech_to_text#329] opened 2022-07-21 04:12 UTC
Hey guys!

Running an example app in Safari and getting this error in initialize():
"NoSuchMethodError: method not found: 'k0' (J.h(a).k0 is not a function. (In 'J.h(a).k0(a,b,c,d)', 'J.h(a).k0' is undefined))"

Only in Safari, works like a charm in Chrome. Safari 15.4, macOS 11.6.2, m1.

Any ideas?

**Comment by sowens-csd** [comment] 2022-07-28 14:01
My first thought was that it was something to do with the m1 because that's an easy thing to blame. Unfortunately I can reproduce this error on Safari on an Intel Mac running 12.4 so that's not the cause. 

Are you running from a web deployment or local environment? So far I've only tested running locally and I'm wondering if it could be a problem with resolving files on local. Let me know if you've tried it from a full we deployment.

**Comment by sowens-csd** [comment] 2022-08-03 14:22
Any updates on this?

**Comment by theniceboy** [comment] 2023-03-17 20:03
Any updates on this?

**Closed** 2023-06-26 11:20 UTC
Labels: waiting for response
