### ISSUE TITLE
Inconsistent results on Android/iOS

### ISSUE THREAD

**Issue by ab36245** [csdcorp/speech_to_text#60] opened 2020-04-03 07:17 UTC
Hi,

I'm using 2.0.1 and seeing inconsistent behaviour between an iPhone (6S) and a Pixel 3a.

I have partialResults set to true for each listen. On both devices I get a rapid stream of partial notifications (i.e. the onResult handler is called with a StreamRecognitionResult with finalResult set to false) when I start to speak.

On Android, as soon as I pause my speech for ~ 1 second the onStatus handler is called with "notListening" and then the onResult handler is called again with finalResult set to true.

On iOS, nothing happens after I finish speaking. Eventually (seems to be consistently just under a minute later) the onResult handler is called with finalResult set to true. The onStatus handler is not called.

I have some simple debug on each handler. Here is the Android trace:

I/flutter (24224): 18:00:27.868 Initializing SpeechToText
I/flutter (24224): 18:00:27.891 _available is true
I/flutter (24224): 18:00:27.891 Calling listen()
I/flutter (24224): 18:00:27.903 onStatus: status listening
I/flutter (24224): 18:00:31.917 onResult: not final: ""
I/flutter (24224): 18:00:32.150 onResult: not final: ""
I/flutter (24224): 18:00:32.426 onResult: not final: ""
I/flutter (24224): 18:00:32.684 onResult: not final: ""
I/flutter (24224): 18:00:32.919 onResult: not final: ""
I/flutter (24224): 18:00:33.164 onResult: not final: "can"
I/flutter (24224): 18:00:33.169 onResult: not final: "can"
I/flutter (24224): 18:00:33.433 onResult: not final: "can you"
I/flutter (24224): 18:00:33.466 onResult: not final: "can you"
I/flutter (24224): 18:00:33.628 onResult: not final: "can you make"
I/flutter (24224): 18:00:33.877 onResult: not final: "can you make"
I/flutter (24224): 18:00:34.087 onResult: not final: "can you make"
I/flutter (24224): 18:00:34.140 onResult: not final: "can you make sense"
I/flutter (24224): 18:00:34.330 onResult: not final: "can you make sense"
I/flutter (24224): 18:00:34.341 onResult: not final: "can you make sense of"
I/flutter (24224): 18:00:34.377 onResult: not final: "can you make sense of"
I/flutter (24224): 18:00:34.568 onResult: not final: "can you make sense of"
I/flutter (24224): 18:00:34.573 onResult: not final: "can you make sense of"
I/flutter (24224): 18:00:35.989 onStatus: status notListening
I/flutter (24224): 18:00:36.480 onResult: final: "can you make sense of it long sentence"

And here is the equivalent on iOS:

flutter: 18:03:24.429 Initializing SpeechToText
flutter: 18:03:24.500 _available is true
flutter: 18:03:24.504 Calling listen()
flutter: 18:03:25.024 onStatus: status listening
flutter: 18:03:27.127 onResult: not final: "Can"
flutter: 18:03:27.292 onResult: not final: "Can you"
flutter: 18:03:27.477 onResult: not final: "Can you make"
flutter: 18:03:27.701 onResult: not final: "Can you make sense"
flutter: 18:03:27.857 onResult: not final: "Can you make sense of"
flutter: 18:03:28.009 onResult: not final: "Can you make sense of this"
flutter: 18:03:28.214 onResult: not final: "Can you make sense of this long"
flutter: 18:03:28.687 onResult: not final: "Can you make sense of this long sentence"
flutter: 18:03:28.785 onResult: not final: "Can you make sense of this long sentence"
flutter: 18:04:25.351 onResult: not final: "Can you make sense of this long sentence"
flutter: 18:04:25.604 onResult: final: "Can you make sense of this long sentence"

Notice the long delay between the third and second last lines of the debug. After a delay of 57 seconds a non-final notification is triggered followed almost immediately by a final one.

Also notice that there is no “notListening” call to the onStatus handler.

Could this possibly have anything to do with version 2’s attempts to remove duplicate results? Or am I meant to set a timer and force a timeout on iOS? I have played with the listenFor setting but it doesn’t seem to have much effect on either device.

One final question, there still seem to be lots of duplicate (non-final) results being passed. Is that working as intended?

**Comment by ab36245** [comment] 2020-04-03 07:24
For completeness here is a similar test on Android with the debugLogging flag set to true:

I/flutter (24934): 18:19:05.487 Calling listen()
D/SpeechToTextPlugin(24934): Start listening
D/SpeechToTextPlugin(24934): setupRecognizerIntent
D/SpeechToTextPlugin(24934): Notify listening
D/SpeechToTextPlugin(24934): Notify listening done
D/SpeechToTextPlugin(24934): Start listening done
I/flutter (24934): 18:19:05.496 onStatus: status listening
D/SpeechToTextPlugin(24934): Calling results callback
I/flutter (24934): 18:19:10.057 onResult: not final: ""
D/SpeechToTextPlugin(24934): Calling results callback
I/flutter (24934): 18:19:10.282 onResult: not final: ""
D/SpeechToTextPlugin(24934): Calling results callback
I/flutter (24934): 18:19:10.304 onResult: not final: ""
D/SpeechToTextPlugin(24934): Calling results callback
I/flutter (24934): 18:19:10.591 onResult: not final: ""
D/SpeechToTextPlugin(24934): Calling results callback
I/flutter (24934): 18:19:10.804 onResult: not final: ""
D/SpeechToTextPlugin(24934): Calling results callback
I/flutter (24934): 18:19:10.811 onResult: not final: ""
D/SpeechToTextPlugin(24934): Calling results callback
I/flutter (24934): 18:19:11.185 onResult: not final: ""
D/SpeechToTextPlugin(24934): Calling results callback
I/flutter (24934): 18:19:11.196 onResult: not final: "this"
D/SpeechToTextPlugin(24934): Calling results callback
I/flutter (24934): 18:19:11.447 onResult: not final: "this"
D/SpeechToTextPlugin(24934): Calling results callback
I/flutter (24934): 18:19:11.451 onResult: not final: "this is"
D/SpeechToTextPlugin(24934): Calling results callback
I/flutter (24934): 18:19:11.727 onResult: not final: "this is"
D/SpeechToTextPlugin(24934): Calling results callback
I/flutter (24934): 18:19:11.971 onResult: not final: "this is also"
D/SpeechToTextPlugin(24934): Calling results callback
I/flutter (24934): 18:19:11.976 onResult: not final: "this is also"
D/SpeechToTextPlugin(24934): Calling results callback
I/flutter (24934): 18:19:12.213 onResult: not final: "this is also"
D/SpeechToTextPlugin(24934): Notify listening
D/SpeechToTextPlugin(24934): Notify listening done
I/flutter (24934): 18:19:13.361 onStatus: status notListening
D/SpeechToTextPlugin(24934): Calling results callback
I/flutter (24934): 18:19:13.656 onResult: final: "this is also a long sentence"
D/SpeechToTextPlugin(24934): Calling results callback
I/flutter (24934): 18:19:13.761 onResult: final: "this is also a long sentence"

Unfortunately setting debugLogging doesn’t seem to do anything on iOS. I don’t get any D/SpeechToTextPlugin lines in the output.

**Comment by sowens-csd** [comment] 2020-04-03 11:51
Most of this is 'working as intended'. The speech recognition subsystems on Android and iOS are very different and the Android capability has limited customization from what I've found so far. In particular Android is very quick to stop listening on pauses in speech and the options that are supposed to control it don't seem to have any effect. The duplicates come from the native speech subsystem so I don't think it would be desirable to filter them out, although it's definitely something I'm thinking about how to improve. 

You should be able to use the listenFor parameter to terminate the iOS listening earlier, if that's not working it's a bug. The lack of a notListening call to the status handler sounds like a problem. I'll look into that.

**Comment by ab36245** [comment] 2020-04-04 05:31
Sorry, poor testing on my part of the listenFor parameter. It does work on iOS. It doesn't quite achieve my goal though as it seems to do a hard timeout (regardless of any incoming speech) and then a cancel (i.e. not send the finalResult and so no alternates - which I really want). That is:

flutter: 16:10:48.471 Calling listen()
flutter: 16:10:48.959 onStatus: status listening
flutter: 16:10:51.134 onResult: not final: "Can"
flutter: 16:10:51.198 onResult: not final: "Can you"
# hard timeout here - I was still speaking
flutter: 16:10:51.611 onStatus: status notListening

However, I can get close to the Android behaviour on iOS by not using listenFor and instead setting a timer after receipt of each partial result and then calling stop() on timeout. If I set the timer for 1 second the iOS behaviour is pretty close to identical with the Android behaviour. That is:

flutter: 16:13:43.192 Calling listen()
flutter: 16:13:43.414 onStatus: status listening
flutter: 16:13:45.156 onResult: not final: "Can"
flutter: 16:13:45.248 onResult: not final: "Can you"
flutter: 16:13:45.949 onResult: not final: "Can you understand"
flutter: 16:13:46.145 onResult: not final: "Can you understand this"
flutter: 16:13:46.243 onResult: not final: "Can you understand this really"
flutter: 16:13:46.395 onResult: not final: "Can you understand this really long" 
flutter: 16:13:46.764 onResult: not final: "Can you understand this really long sentence"
flutter: 16:13:46.863 onResult: not final: "Can you understand this really long sentence"
flutter: 16:13:47.873 the timer went off
flutter: 16:13:47.963 onStatus: status notListening
flutter: 16:13:48.103 onResult: not final: "Can you understand this really long sentence"
flutter: 16:13:48.155 onResult: final: "Can you understand this really long sentence" (7 alternate(s))

As you can see, this fires the statusHandler and then provides a finalResult, alternates and all. Great!
With this in place I can configure the app to stop listening after a period of silence which is what I want. Is it worth considering providing a "stopAfter" option (taking a Duration) to listen() to save the user having to fiddle with timers? Just a thought.

So now I can get iOS behaving as I want but it's harder with Android. Android already applies a 1 second timeout after I finish speaking which means I can't configure the behaviour for anything longer. From what you say this appears to be impossible to change?

**Comment by sowens-csd** [comment] 2020-04-04 11:53
Thanks for the update, that's better news. Yes, I think that being able to configure whether to stop or cancel after the timeout is a good idea. I'll add that as a feature idea. 

I wouldn't say it's impossible to change the Android behaviour but it is not supported, or made easy, by the Android Speech Recognition subsystem. There are options that claim to configured the timeout but even the official docs say they may be ignored, and they are in fact ignored. There appear to be some ways to make it appear to do this, but they involve waiting for it to stop and then automatically restarting it, while fiddling with background sounds so that the standard Android beeps don't play. I'm not a big fan of that type of hack because they seem brittle in the face of platform changes. However, they are possible and I'm considering if something along these lines would be useful to users of the plugin.

**Comment by sowens-csd** [comment] 2020-04-07 13:55
New release on pub.dev now (2.1.0). It changes the `listenFor` behaviour to stop. I think the other Android behaviour issues are covered by other issues so I'm going to close this. Please try out the new version and let me know if you have other comments.

**Closed by sowens-csd** 2020-04-07 13:55 UTC

**Comment by ab36245** [comment] 2020-04-13 11:20
It's taken me a while to get to this. I can confirm that the listenFor seems to generate a stop rather than a cancel. Thanks!
