### ISSUE TITLE
Restart problems

### ISSUE THREAD

**Issue by ab36245** [csdcorp/speech_to_text#65] opened 2020-04-13 11:41 UTC
I'm trying to develop an app which listens for input briefly, stops after a brief pause in speech to process the input (kind of in the way the native Android implementation does already, but without the annoying mic on/mic off sound effects) and then listens again for the next speech input.

I can get close on iOS by timing out after a brief pause, stopping listening to generate the finalResponse (the alternates matter to me so I want these) and then restarting listening.

This goes pretty well except for two problems.

The first problem is that on iOS the listen shuts down after about a minute. The only way I can detect this is to use the onStatus hook and restart listening if necessary. This approach generally works well. However, occasionally the listener almost immediately (10s of milliseconds) stops again. Once this happens it never reverts to listening properly again. Every time listen is started again it stops (with a call to onStatus "notListening" again) after 10s of milliseconds. In these circumstances I've tried reinitializing just in case that helped but it doesn't.  Basically speech recognition becomes impossible after this point until an app restart.

Curiously I see this most frequently in the (iOS) simulator (I get it quite a lot) but it seems less frequent (but does occur) on a real device (I test less frequently with real devices because the build and deploy cycle is slower).

Have you seen odd behaviour where the listener goes to notListening very soon after being re-started? Do you have any suggestions to improve the stability of this? Is my frequent listening, stopping and restarting a fundamental problem?

The second problem is independent of this one (I think) so I'll raise a separate issue.

Thanks!

**Comment by sowens-csd** [comment] 2020-04-15 12:42
I haven't seen this behaviour but it is definitely interesting. I'll add some logging to the iOS implementation and have you retest to see if we can pin down what's happening. 

I believe that there are limits to how often applications are allowed to use the speech recognition subsystem, those limits are not described however. The documentation says things like 'too often', basically allowing Apple to decide. It may also be network or other issues, though I wouldn't have thought those would be an issue in the simulator.

**Comment by ab36245** [comment] 2020-04-16 04:24
Sounds good. Let me know when you have something for me to test.

**Comment by sowens-csd** [comment] 2020-04-18 13:28
The current version in the repo is ready to try. You'll have to either run it in Xcode or use Console to see the debug and other messages. In Xcode the messages will show up in output window while debugging. 

The subsystem is com.csdcorp.speechToText and the category is plugin if you're using Console. There's a good article here https://www.avanderlee.com/debugging/oslog-unified-logging/ if you haven't done it before. 

Here's an example of the messages in Xcode:
2020-04-18 09:23:56.295076-0400 Runner[12549:179650] [plugin] Has permissions continuing with setup

**Comment by ab36245** [comment] 2020-04-19 03:35
Thanks. I should be able to try this on Monday.

**Comment by ab36245** [comment] 2020-04-23 04:53
Sorry, been dragged into another couple of issues. Should get back to this in a few days...

**Comment by sowens-csd** [comment] 2020-05-19 12:35
I'm going to close this issue as I can't reproduce. Please open a new issue if you're still having problems.

**Closed by sowens-csd** 2020-05-19 12:35 UTC
Labels: Could not reproduce, bug, waiting for response
