### ISSUE TITLE
Wireless headsets support

### ISSUE THREAD

**Issue by rayrapetyan** [csdcorp/speech_to_text#210] opened 2021-05-09 02:53 UTC
Hello. It would be nice to have a support for a wireless headsets (currently only default device's microphone is utilized).

At least for Android it should be as simple as adding few lines of code:

https://stackoverflow.com/questions/28086403/android-speech-recognizer-with-bluetooth-microphone
https://stackoverflow.com/questions/8681085/android-voice-recognition-through-bluetooth

I haven't tried them though.

The question is if it's also easy to do the same on iOS.

Thanks.

**Comment by sowens-csd** [comment] 2021-05-11 11:44
AFAIK wired headsets already work fine because they become the default when plugged in. I've definitely used them on iOS though not on Android. Have you tried it? I 

I haven't tried Bluetooth. I guess that you did and it doesn't work? Did you try on both Android and iOS?

**Comment by rayrapetyan** [comment] 2021-05-14 03:02
Thanks Stephen! Just curious - how did you tested wired headset, I mean when it's plugged in your phone is nearby anyway, so how do you know headset's mic (and not the built-in microphone) was used?

I tried BT on Android and yeah, it doesn't work. My BT mic doesn't work even on the in-system voice input (e.g. when you use mic on a standard google keyboard voice input). It works (and turns on automatically) only on incoming call (in any app supporting calls). I think this is all by design and that's how it's expected to work. At the same time I'm sure BT mic can be turned on explicitly (using steps from links above).

**Comment by rayrapetyan** [comment] 2021-05-14 03:14
There is one thing I'm afraid will not work though... Every time I test my mic at e.g. https://mictests.com/, I can hear "Call ended" at the end of test. So if it's a hardware feature, it might be hard to disable programmatically (if at all possible).

**Comment by rayrapetyan** [comment] 2021-05-14 03:41
UPD: I've just tested a wired headset and mic becomes default, I've scratched the mic while recording so I'm 100% sure it works. Tried few more BT - none of them work with this plugin. Also, not all BT say "call ended" at https://mictests.com, so I think it's configurable from the headsets supporting tools\apps.

**Comment by sylvainjack** [comment] 2021-11-05 08:06
Hi everyone, 
I encounter the same problem with apple AIRPODS : speech to text doesn't work. In the same app, I use tts_ (text to speech) and have the same problem. The sound won't go through the AirPods.
Has anyone found a way to solve this problem ?

**Comment by sowens-csd** [comment] 2021-12-10 15:25
Current state of this is that @sylvainjack's suggested fix is released os Bluetooth should be working on iOS. The Android version needs updates to properly support Bluetooth.

**Comment by sowens-csd** [comment] 2021-12-11 16:32
Android support for bluetooth is now in the repo version. If anyone has a chance to test it that would be welcome. I've tried it on a Samsung with headphones and it seems to be working.

**Comment by rayrapetyan** [comment] 2021-12-11 21:06
Thanks, tested it today.
By itself it works fine, but when https://pub.dev/packages/text_to_speech is also used, occasionally output voice becomes muted (you can't hear anything in headphones nor from speaker). Calling "setVolume" right before "speak" doesn't help. What could be the reason?

**Comment by sowens-csd** [comment] 2021-12-12 14:45
Thanks for testing it so quickly. Does the volume issue only happen if you are using a Bluetooth device or does it happen even if you have bluetooth turned off completely?

**Comment by acme-im** [comment] 2021-12-12 16:31
Only when Bluetooth device is connected and used.

**Comment by rayrapetyan** [comment] 2021-12-12 16:32
Only when Bluetooth device is connected and used.

**Comment by sowens-csd** [comment] 2021-12-13 15:09
Thanks, I'll try to reproduce and see what I can do. In general volume issues on Android are painful.

**Comment by sowens-csd** [comment] 2021-12-14 15:53
I think I have a reproduce but for me it is happening every second phrase. So I start a listen, then use `speak` to play back what I just said. The first time it works properly, the second time it is either very low volume or not working at all, not sure which. That pattern then repeats. Do you see the same behaviour or different?

**Comment by sowens-csd** [comment] 2021-12-14 16:40
Excellent, glad yours is the same. 

Okay, I've just committed a potential fix. It resolves the issue for me. I was only stopping the bluetooth headset on an explicit stop or cancel. This version stops it every time speech ends. Let me know if this works for you.

**Comment by rayrapetyan** [comment] 2021-12-17 23:39
It works now, thanks!

**Comment by sowens-csd** [comment] 2021-12-18 13:27
This is published as 5.4.0 on pub.dev. Thanks for the help verifying this!

**Closed by sowens-csd** 2021-12-18 13:27 UTC
Labels: enhancement, android
