### ISSUE TITLE
Web Support Issue

### ISSUE THREAD

**Issue by imcoffeefreak** [csdcorp/speech_to_text#250] opened 2021-08-03 09:58 UTC
The following error is shown inside when the result is received.

**errors.dart:187 Uncaught Error: Expected a value of type 'SpeechRecognitionEvent$', but got one of type 'Event$'
    at Object.throw_ [as throw] (errors.dart:236)
    at Object.castError (errors.dart:84)
    at Object.cast [as as] (operations.dart:442)
    at Function.as_C [as as] (classes.dart:635)
    at Object._argumentErrors (operations.dart:197)
    at Object._checkAndCall (operations.dart:318)
    at Object.dcall (operations.dart:329)
    at SpeechRecognition.<anonymous> (html_dart2js.dart:37283)**

**Comment by sowens-csd** [comment] 2021-08-03 11:44
Duplicate of #242

**Comment by sowens-csd** [comment] 2021-08-03 11:46
I just re-read this and it might not be a duplicate. What version of Flutter and the plugin are you using and which browser / OS are you seeing this on?

**Comment by imcoffeefreak** [comment] 2021-08-03 16:05
@sowens-csd

Flutter version : 2.0.5
speech_to_text: 4.2.2 
OS: Windows
Browser: Chrome

**Comment by imcoffeefreak** [comment] 2021-08-25 06:27
@sowens-csd 

I think this can be closed. this issue only happens in localhost. Works fine in production

**Closed** 2021-12-10 15:20 UTC
Labels: duplicate
