### ISSUE TITLE
Incompability with new null-safety plugins

### ISSUE THREAD

**Issue by AlexanderShirokih** [csdcorp/speech_to_text#178] opened 2021-03-07 17:26 UTC
Since Flutter 2.0 released, I decided to use new null-safety feature and upgrade all available dependencies with null-safety support. But now i can't build my project because of version solving error.
I got the next error message:
`Because firebase_crashlytics >=1.0.0 depends on firebase_crashlytics_platform_interface ^2.0.0 which depends on plugin_platform_interface ^2.0.0, firebase_crashlytics >=1.0.0 requires plugin_platform_interface ^2.0.0.
And because speech_to_text_platform_interface 1.4.2 depends on plugin_platform_interface ^1.0.1 and no versions of speech_to_text_platform_interface match >1.4.2 <2.0.0, firebase_crashlytics >=1.0.0 is incompatible with speech_to_text_platform_interface ^1.4.2.
And because speech_to_text 3.1.0 depends on speech_to_text_platform_interface ^1.4.2 and no versions of speech_to_text match >3.1.0 <4.0.0, firebase_crashlytics >=1.0.0 is incompatible with speech_to_text ^3.1.0.
So, because [my_project_name] depends on both speech_to_text ^3.1.0 and firebase_crashlytics ^1.0.0, version solving failed.
pub get failed.`

**Comment by kaladron** [comment] 2021-03-07 18:55
This is a dupe of #164

**Comment by sowens-csd** [comment] 2021-03-07 21:13
The error is correct. You can switch to a repo dependency on the `null-safety` branch but it's not quite ready for prime time. @kaladron has done some good work moving this along and I've been slow in responding. Hopefully not too much longer. I'm going to close this issue and you can track our progress on #164.

**Closed by sowens-csd** 2021-03-07 21:13 UTC
