### ISSUE TITLE
Question: Support Flutter Web?

### ISSUE THREAD

**Issue by Gene-Dana** [csdcorp/speech_to_text#107] opened 2020-06-23 14:12 UTC
Just wondering if this would work in something like Flutter Web to expose the methods of a browser like chrome!

**Comment by sowens-csd** [comment] 2020-06-23 14:26
Not yet, but it's an interesting idea. Do you know if Chrome (or other) browsers have speech recognition capabilities natively? Do you have any links?

**Comment by hakandilek** [comment] 2020-06-23 17:59
hope this helps: https://wicg.github.io/speech-api/

**Comment by Gene-Dana** [comment] 2020-06-26 03:59
> Not yet, but it's an interesting idea. Do you know if Chrome (or other) browsers have speech recognition capabilities natively? Do you have any links?

Yes, Chrome is the only browser that has implemented it so far!

**Comment by Xx0w0wxX** [comment] 2020-07-29 12:09
I cannot wait for Flutter Web. SpeechToText is awesome. Work hard

**Comment by TobiasHeidingsfeld** [comment] 2020-08-26 07:38
More love for Flutter Web. If I would find the time to implement this would you accept a pull request?

**Comment by sowens-csd** [comment] 2020-08-26 12:05
Definitely! Always happy to have contributions. With the usual proviso that I'd review it for general code cleanliness and other goodness on the way in to make sure I could support it.

**Comment by kofoednielsen** [comment] 2020-10-26 14:15
How would you feel about using an online stt provider for web support?

**Comment by sowens-csd** [comment] 2020-11-14 12:27
The problem is that it requires separate accounts and usually there's a cost associated with it. It would make the web implementation very different from the iOS or Android. If there were a lot of interest in using online STT then adding it as an option for any deploy target might make sense.

**Comment by sowens-csd** [comment] 2020-11-14 14:02
For those watching this issue the 3.0.0 version which is in main now is work in progress towards supporting this. It breaks out the platform interface so that it can be reimplemented for web. So, web support is not here yet but it is progressing.

**Comment by Nicicalu** [comment] 2021-01-19 20:31
I'd love that! The only thing missing for me

**Comment by sowens-csd** [comment] 2021-02-08 13:26
The current version on main has support for web if anyone wants to give it a try. I still need to add platform capability tests so that the plugin can report failure on browsers that don't support speech yet. Looks like right now Chrome and Edge support it.

**Comment by Nicicalu** [comment] 2021-02-08 19:46
@sowens-csd Thanks so much! I have one problem though. When I launch the app (even your example web app) it throws this error. I ran it on chrome V88 and edge (Chromium) V88. Let me know if you need any more info
 
Error: Expected a value of type 'JSObject<Event>', but got one of type 'Event$'
    at Object.throw_ [as throw] (http://localhost:53511/dart_sdk.js:5306:11)
    at Object.castError (http://localhost:53511/dart_sdk.js:5277:15)
    at Object.cast [as as] (http://localhost:53511/dart_sdk.js:5593:17)
    at dart.LegacyType.new.as (http://localhost:53511/dart_sdk.js:7191:60)
    at Object._argumentErrors (http://localhost:53511/dart_sdk.js:5429:19)
    at Object._checkAndCall (http://localhost:53511/dart_sdk.js:5512:29)
    at Object.dcall (http://localhost:53511/dart_sdk.js:5521:17)
    at SpeechRecognition.ret (http://localhost:53511/dart_sdk.js:60934:21)

**Comment by rodion-m** [comment] 2021-02-08 20:07
Same error as @Nicicalu

**Comment by sowens-csd** [comment] 2021-02-09 15:06
Thanks so much for trying it out, I really appreciate it. Did you run the new `multi_platform_example/lib/main.dart` app? And what Flutter channel were you running? I used beta. 

Also, and I know this shouldn't matter, but just so I have all the details, what OS are you running it on? I've tried it on Chrome Version 88.0.4324.96 (Official Build) (x86_64) running on Big Sur.

**Comment by Nicicalu** [comment] 2021-02-09 15:30
@sowens-csd I am running dev channel. But ran the `multi_platform_example/lib/speech_main.dart` file because you added this file in your newest commit.

**Comment by Nicicalu** [comment] 2021-02-09 16:31
Ok, I tested it on the beta channel and the launching the `main.dart` worked. :)

**Comment by sowens-csd** [comment] 2021-02-09 18:33
Thanks for the feedback. I'll see what's going on with the beta upgrade, hopefully not too serious.

**Comment by Nicicalu** [comment] 2021-02-09 20:28
@sowens-csd Thanks for your quick response! I am working on a school project where I use your library. Thanks<3

**Comment by sowens-csd** [comment] 2021-02-15 14:10
Should be resolved now in the version in the repo. Getting closer to a release version. Flutter added native support for some of the underlying speech events in that beta upgrade so there were type conflicts.

**Comment by Nicicalu** [comment] 2021-02-15 16:12
@sowens-csd I tested it and it worked fine! :) Thank you. Do you know if it's possible, that you can say words of different languages in one sentence? Like "Translate me Bahnhof to english".

**Comment by sowens-csd** [comment] 2021-02-15 16:22
Thanks for the quick feedback, glad it's working. I better release before the Flutter team breaks it again. 

As far as I know that is not supported by any of the speech recognition systems other than some 'adopted' words that are effectively native to that language, like _hors d'oeuvres_ used in English.

**Comment by Nicicalu** [comment] 2021-02-15 16:57
How would you create a translator using this plugin? Any tips? :)

**Comment by sowens-csd** [comment] 2021-02-15 17:46
I suppose I'd look at something like this https://cloud.google.com/translate or https://aws.amazon.com/translate/ fronted with speech recognition to create the text to send to the API. Both of those have fairly generous free tiers so they would be fine for a school project for example.

**Comment by Nicicalu** [comment] 2021-02-15 18:18
@sowens-csd Thanks for this information. My problem is, that translation should be one of many functions (Like a voice assistant). But I think I can get creative and combine it with these cloud services. Thanks again :)

**Comment by amin-531** [comment] 2021-02-16 00:27
Hi, I use version 3.2.0 and works fine on android with all locales, but on web when I change locale it has no effect and recognize English again... there is limitation on locales on web ?

**Comment by sowens-csd** [comment] 2021-02-17 16:21
Not a limitation, more of a bug. Can you try it with the fix I just committed? I haven't tested it yet because I'm on a different version of Flutter but it should resolve the issue.

**Comment by Nicicalu** [comment] 2021-02-18 20:53
@sowens-csd For me it didn't work, I used your example, where there is a dropdown for the locales. On web it isn't working, even with the new commit. (At least for me)

**Comment by amin-531** [comment] 2021-02-18 23:01
@sowens-csd It works for me, thanks a lot...

**Comment by amin-531** [comment] 2021-02-18 23:06
> 
> 
> Not a limitation, more of a bug. Can you try it with the fix I just committed? I haven't tested it yet because I'm on a different version of Flutter but it should resolve the issue.

@sowens-csd It works for me, thanks a lot...

**Comment by Nicicalu** [comment] 2021-02-19 11:11
@sowens-csd Now it is fixed on english. In the old version it was on german, because my browser is.

**Comment by sowens-csd** [comment] 2021-03-15 12:59
web support is available in 4.0.0-nullsafety which is live on pub.dev now. 

I tried French comprehension and it was working, the main issue seems to be getting the language code right. Unlike Android / iOS I haven't yet found a reliable source for the language codes. I hope to resolve that in an upcoming release. So far all I have tested successfully are 'en_US' and 'fr_FR'. @Nicicalu my German is not good enough to test it even if I did know the language code for sure, have you tried just 'de'?

**Comment by Nicicalu** [comment] 2021-03-15 13:21
@sowens-csd Thanks for your answer. It looks like it's working with the newest version (4.0.0-nullsafety). Thank you for your constant effort. 🎉

**Comment by Gene-Dana** [comment] 2021-03-15 15:44
Guys, this makes me so happy !

**Comment by Gene-Dana** [comment] 2021-03-15 15:44
Should I close the issue now?

**Comment by Nicicalu** [comment] 2021-03-15 16:40
Yes, everything works for me ;)

**Comment by sowens-csd** [comment] 2021-03-15 17:01
Hearing that makes me happy, thanks! And yes, @Gene-Dana, please feel free to close. Always satisfying.

**Closed** 2021-03-22 12:54 UTC
Labels: enhancement, waiting for response

**Comment by sk92129** [comment] 2024-01-31 15:48
Are there any list of web browsers that this plugin should work in theory?  desktop browsers and mobile browsers, edge, safari, etc.

**Comment by sowens-csd** [comment] 2024-01-31 15:53
The plugin should support any browsers that support the web speech recognition standard. There's a section in the README with the info I've found on it.
