### ISSUE TITLE
Locales method only gets the selected language

### ISSUE THREAD

**Issue by DanielCorreia07** [csdcorp/speech_to_text#257] opened 2021-08-30 17:47 UTC
Hi,

First of all, let me thank you for the work done on this plugin.

Now, the issue:

I'm currently testing an app on a Samsung S20+ 5G with android 11 and I should be getting more than one language when calling "locales()".

I have been setting up languages on the device but the result is always the same.

Here are some screenshots of the device settings:
![settings](https://user-images.githubusercontent.com/34482565/131379677-5357d526-a478-4f9b-a67a-37f9ea30c8b1.png)

This is my debug log on initializing:
![image](https://user-images.githubusercontent.com/34482565/131379903-63bec536-2979-45b9-956d-c334148953aa.png)

This is the log that I get when I call "locales" method:
![image](https://user-images.githubusercontent.com/34482565/131466147-1c7a531f-d99a-4778-8ef0-1f83be0a9d70.png)

This is a screenshot with a breaking point on the "locales" method:
![image](https://user-images.githubusercontent.com/34482565/131380406-1f8ffb51-951c-4b28-a60e-84aeff289fb6.png)

Debugging on native android code, in case that you can't replicate:
On "locales" native method, the first attempt to get the "Voice Details Intent" it comes null:
![image](https://user-images.githubusercontent.com/34482565/131477581-1615f53b-da68-4aa4-bdfa-7daf7cd06fac.png)

On the second attempt, it returns an intent but it has no extras:
![image](https://user-images.githubusercontent.com/34482565/131477772-7b3f838e-97ef-4391-a75a-70825e46d8ad.png)

And then on the broadcast receiver side, the results are, as expected, just an empty bundle:
![image](https://user-images.githubusercontent.com/34482565/131478219-6e00efd4-99b9-4496-a828-b41da14d8ae7.png)

I have tested it on others devices with android 11 and it works fine.
I using v5.0.0 the most recent version on this day.

Sorry for the long and detailed post, but I in case that you are not able to reproduce it, I'm hopping that all the info provided can help you.

Thanks.

**Comment by sowens-csd** [comment] 2021-09-09 19:06
Thanks for the very detailed post. That's a very odd result. The fact that it's working on other Android 11 devices means that it's probably not an OS version issue. The fact that the intent is returning null on the first attempt is strange. When that returns null can you let me know if pluginContext has a value? 

Is speech recognition working on the device for the one language that is being returned? Is en_US the language that is set as the default on that device? If you try setting a language code for a language that you believe is installed but is not being returned does speech recognition work properly for that language?

**Comment by DanielCorreia07** [comment] 2021-09-10 08:06
Hi, I agree with you when you think that's not an OS version issue. I think it's a Samsung issue due to their customized ROM.

I'm not an expert in the "ROM World", I'm sorry if I'm saying something wrong.

To answer your questions:

> When that returns null can you let me know if pluginContext has a value?

Yes.

![image](https://user-images.githubusercontent.com/34482565/132820245-c5a6a1fc-2ec6-4871-9fe8-228cf152ab53.png)


> Is speech recognition working on the device for the one language that is being returned?

Yes.

> Is en_US the language that is set as the default on that device?

Yes. It's the default, and it's the only language being returned.

>  If you try setting a language code for a language that you believe is installed but is not being returned does speech recognition work properly for that language?

Yes, on the first image I have "Portuguese (pt_PT)" installed, and yes, it worked for Portuguese.

**Comment by sowens-csd** [comment] 2021-09-12 11:06
Looks like this issue might be related, but no solutions are listed here: https://www.reddit.com/r/programminganswers/comments/25rd1k/why_might/

Worth checking if Voice Search is installed on that device since that's listed as a possible cause for the intent returning null.

**Comment by sowens-csd** [comment] 2021-09-12 11:45
I just committed a change that might resolve the issue according to this post: https://stackoverflow.com/questions/48500077/recognizerintent-action-get-language-details-in-oreo

I can't reproduce the issue in my test devices because I get the intent for context. However I did confirm that if I force it to use the null intent branch it works properly with this change. If you could try it on the device that does show the issue that would be helpful. You'll have to use the current version from the repo to see the change.

**Comment by DanielCorreia07** [comment] 2021-09-13 07:47
Yes, it works!

![image](https://user-images.githubusercontent.com/34482565/133043857-6b0681df-03c9-4c18-936b-30e4af44c529.png)

Thanks :)

**Comment by sowens-csd** [comment] 2021-09-13 14:52
Thanks for letting me know, that's great. This is now live as 5.1.0 on pub.dev. Thanks very much for your help with this.

**Closed by sowens-csd** 2021-09-13 14:52 UTC
Labels: waiting for response
