### ISSUE TITLE
Run from example app opens and initializes but fails when pressing "Start"

### ISSUE THREAD

**Issue by notricks9** [csdcorp/speech_to_text#77] opened 2020-04-27 19:47 UTC
Hello,

I downloaded the example app from Git and when I run the app, it opens up, I can click initialize, but then when I click 'Start' I see an error:  Error Status error_network - true

Any ideas how to fix this?

Thank you!

**Comment by sowens-csd** [comment] 2020-04-27 20:34
For Android the example only works on a real device. For both Android and iOS speech recognition requires an active Internet connection.

**Comment by notricks9** [comment] 2020-04-27 20:50
Ok.  Can you tell me if I will be able to accomplish this?

User will push a button and then the entire process will run.

1. TextToSpeech will say "What is your first name"
2. SpeechToText will wait for input and then continue automatically to the next.
3. TextToSpeech will say "Hi " + firstname + "Thank you for using this app, what is your age"
4. SpeechToText will wait for input.
ETC.
ETC.
ETC.

I have the TextToSpeech working, but am not sure if your SpeechToText will do this correctly.

Thoughts?

Thank you!

Scott

**Comment by sowens-csd** [comment] 2020-04-28 11:53
Yes, that should work just fine. You'll need to listen for the end of speech event from TextToSpeech before triggering the listen on SpeechToText. Then you'll need to either wait for some set of expected content or a maximum duration, or a pause between utterances, in SpeechToText to end the listen session and start the next TextToSpeech segment. I do similar sequences in my applications. 

I'm going to close this issue since the original issue is expected behaviour. Unless you are still having problems?

**Closed** 2020-04-29 11:15 UTC
Labels: expected-behaviour
