### ISSUE TITLE
How can I listening continously

### ISSUE THREAD

**Issue by yalda-student** [csdcorp/speech_to_text#339] opened 2022-09-19 14:21 UTC
Hello,
 I used this great package, but I faced a problem; It couldn't listen continously and it stopped after a few seconds. Is there any way to fix it?
Thank you in advance :)

**Comment by sowens-csd** [comment] 2022-09-19 20:03
Glad you're enjoying the plugin. 

This is a duplicate of #253 where there's a lengthy discussion and some code samples. The short answer is that the plugin isn't really designed for this use because iOS and Android don't support that use well, however you can kind of make it work.

**Closed by sowens-csd** 2022-09-19 20:03 UTC
Labels: duplicate
