### ISSUE TITLE
Only one initialize at a time

### ISSUE THREAD

**Issue by jheimes-silveira** [csdcorp/speech_to_text#19] opened 2019-12-30 14:33 UTC
I observe the following behavior, if I am using lib for the first time and do not apply the permission, I cannot change the initialize method as it loops in the following error.

Only one initialize at a time

The way I found to request permission more than once if the user did not grant permission was to remove the following code snippet.
```
         if (null! = activeResult) {
             result.error (SpeechToTextErrors.multipleRequests.name,
                     "Only one initialize at a time", null)
             return
         }
```
I think a lot of other people must be going through the same problem as mine.

**Comment by sowens-csd** [comment] 2019-12-30 15:09
I haven't seen that behaviour. Can you give me a few more details on the error sequence? 

The plugin should only allow a single initialize at a time, but it should be returning failure or success in all cases and clearing the active result. I just had a look and the only case I can see where that could happen is if the user doesn't select either Allow/Deny on the system dialog, but that doesn't seem like a valid case so I must be missing something. Can you give me a set of steps to reproduce?

**Comment by jheimes-silveira** [comment] 2019-12-30 15:15
If this is the first time I'm accessing the app and I don't click allow, I can't open or mark permission anymore.

**Comment by sowens-csd** [comment] 2019-12-30 16:02
I've uploaded a change to the example to allow you to try initialize multiple times. For me, at least on an Android emulator, it works as expected. You can click 'Initialize' and then deny and try again. Could you give that a try and let me know if it's working for you and if it is different than what you're seeing in your application? The new version is only in Github right now so you'll have to grab it from there. It's only the example/lib/main.dart that is different.

**Comment by jheimes-silveira** [comment] 2019-12-30 16:09
yes

**Comment by sowens-csd** [comment] 2020-01-03 12:22
Since that works for you I can close this? Or is there still an issue?

**Comment by sowens-csd** [comment] 2020-01-06 18:54
Closing since this seems like the issue is resolved.

**Closed by sowens-csd** 2020-01-06 18:54 UTC
Labels: waiting for response
