### ISSUE TITLE
callback error of result.final variable Result

### ISSUE THREAD

**Issue by EllenGuissoni** [csdcorp/speech_to_text#16] opened 2019-12-27 17:38 UTC
I'm testing with an iOS version 13.2.3 and noticed that the result.finalResult variable is always returning me with the false value even at the end of the audio capture, but when I test with android the result.finalResult variable returns me the value true

**Comment by sowens-csd** [comment] 2019-12-27 19:23
On the example app on iOS 13.3 it returns true as expected when stop is called. If you call cancel it return false. One difference I've noticed between the iOS and Android speech recognition is that Android auto cancels after a fairly short wait and will return true on the result at that time. Perhaps that's what you're seeing?

**Comment by sowens-csd** [comment] 2020-01-06 18:55
Closing as this seems to be working as intended. Feel free to provide more details if you're still seeing a problem.

**Closed by sowens-csd** 2020-01-06 18:55 UTC
Labels: waiting for response
